[build-system]
requires = ["setuptools>=80.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "antropy"
description = "AntroPy: entropy and complexity of time-series in Python"
readme = "README.rst"
license = {text = "BSD (3-clause)"}
authors = [
    {name = "Raphael Vallat", email = "raphaelvallat9@gmail.com"},
]
maintainers = [
    {name = "Raphael Vallat", email = "raphaelvallat9@gmail.com"},
]
classifiers = [
    "Intended Audience :: Science/Research",
    "Operating System :: MacOS",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Mathematics",
]
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.22.4",
    "scipy>=1.8.0",
    "scikit-learn>=1.2.0",
    "numba>=0.57",
]

[dependency-groups]
dev = ["ruff>=0.9"]
test = [
    "pytest>=7.0",
    "pytest-cov",
    # Ensure coverage is new enough for `source_pkgs`.
    "coverage[toml]>=5.3",
]
docs = [
    "sphinx>7.0.0",
    "pydata-sphinx-theme",
    "numpydoc",
    "sphinx-copybutton",
    "sphinx-design",
]

[project.urls]
Homepage = "https://github.com/raphaelvallat/antropy/"
Downloads = "https://github.com/raphaelvallat/antropy/"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
namespaces = false
where = ["src"]

[tool.setuptools.dynamic]
version = {attr = "antropy.__version__"}

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "--showlocals --durations=10"  # --cov
testpaths = ["tests"]
pythonpath = ["tests"]
doctest_optionflags= ["NORMALIZE_WHITESPACE", "IGNORE_EXCEPTION_DETAIL"]
filterwarnings = [
    "ignore::UserWarning",
    "ignore::RuntimeWarning",
    "ignore::FutureWarning",
]
markers = ["slow"]

[tool.coverage.run]
branch = true
omit = [
    "*/tests/*",
]
source_pkgs = ["antropy"]

[tool.coverage.paths]
source = ["src"]

[tool.coverage.report]
show_missing = true
# sort = "Cover"

[tool.ruff]
line-length = 100
target-version = "py311"
exclude = [
    "notebooks",  # Skip jupyter notebook examples
    "docs",
    "__init__.py",  # Ignore star and unused import violations for __init__.py files
]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "W", "NPY"]
ignore = ["NPY002"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 90
